### ISSUE TITLE
Suggestion: turn off logging of favicon and robots.txt by default

### ISSUE THREAD

**Issue by maxaud** [okor/LEMPress#16]
A suggestion I have would be to turn off the logging of favicon errors and rebots.txt by default:

	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

**Comment by okor** [comment]
Done https://github.com/okor/LEMPress/commit/80e4193e6b9fd7643c1f392fca06baeec4acf722
