### ISSUE TITLE
$_GET params lost on inner pages of site

### ISSUE THREAD

**Issue by maxaud** [okor/LEMPress#17]
I was having an issue where `$_GET` parameters were being lost on inner pages of the WordPress site. I would reference `$_GET` and it was returning null.

I changed the location block to this to pass parameters:
```
	location / {
		index  index.php;
		try_files $uri $uri/ /index.php?$args;
	}
```

would it be wrong to suggest this as the default?

**Comment by okor** [comment]
Done https://github.com/okor/LEMPress/commit/262dea138d5f67b10e58f1ee92e3e4942c4d9f56
