### ISSUE TITLE
ERROR: Server Name -  VirtualHost

### ISSUE THREAD

**Issue by QROkes** [okor/LEMPress#18]
LEMPress-virtualhost.txt

      server_name  URL URL.com;        //ERROR  

This generate a double ".com" when execute the rsync with "sites-available"

     server_name  mydomain.com mydomain.com.com;

**Comment by okor** [comment]
@QROkes Have never seen that before. I know this is ancient but please make a test case and pull request if you're still interested.

**Comment by maxaud** [comment]
I can verify that this problem exists. I always assumed it was  to catch if someone entered the wrong thing when entering a domain.

**Comment by QROkes** [comment]
Sorry guys, this is a very ancient post.
Now I'm using EasyEngine (rtCamp)
