### ISSUE TITLE
PHP5-FPM

### ISSUE THREAD

**Issue by BX-AlexKim** [okor/LEMPress#20]
Hi,
Do you think you can update this script to use php5-fpm?
The current settings do not turn on FPM.

Take a look here:
http://linhost.info/2013/09/502-bad-gateway-nginx-and-php-fpm/

I used these instructions to update the LEMPress install and things are loading much faster. And when I tried to use W3 Total Cache, it slowed down.

So, I am using LEMPress with FPM turned on without W3 Total Cache.

Alex

**Comment by okor** [comment]
@BX-AlexKim If you are still interested, please make a pull request
