### ISSUE TITLE
Any plans?

### ISSUE THREAD

**Issue by maxaud** [okor/LEMPress#22]
Any plans to make this work with Ubuntu 14.04 instead of 12.04?

Been using it a lot but now with Amazon changing things in EC2 they're pushing people towards 14.04.

**Comment by okor** [comment]
@maxaud Have you tried it with 14.04 yet? I haven't and I don't do any work with Wordpress these days. I might be willing to do this however. Could either do it in a 14.04 branch or add it as a build option when initially setting up the server.

**Comment by maxaud** [comment]
I did try it. Didn't seem to work fully. I ended up dropping back to 12.04 I don't think the breakpoint is within the WordPress portion of LEMPress but I could be wrong.

**Comment by okor** [comment]
Yeah, realistically I don't have time to do this. I'm open to pull requests however.
